# Defx --- Dark ppowered file explorer implementation
[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = ['Defx']
hook_add = 'lua require("plugins.defx").hook_add()'
hook_source = 'lua require("plugins.defx").hook_source()'

# Filetype icons for Defx
[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_source = ['defx.nvim']

