# Dark powered asynchronous unite all interfaces for Neovim/Vim8
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['fruzzy']
on_cmd = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord', 'DeniteProjectDir']
on_func = ['denite#']
hook_add = 'lua require("plugins.denite").hook_add()'
hook_source = 'lua require("plugins.denite").hook_source()'

# External denite.nvim mathcer
[[plugins]]
repo = 'raghur/fruzzy'
on_source = ['denite.nvim']
hook_add = 'lua require("plugins.fruzzy").hook_add()'
hook_post_update = 'lua require("plugins.fruzzy").hook_post_update()'

# register/yank for denite
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = ['denite.nvim']

# MRU
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

# Dark powered shell interface for Neovim
[[plugins]]
repo = 'Shougo/deol.nvim'
on_source = ['denite.nvim']
hook_add = '''
  nnoremap <silent> <Space>'  :<C-u>Deol zsh -no-start-insert -split=horizontal<CR>
  nnoremap <silent> <C-t> :<C-u>Denite -buffer-name=deol -split=floating -cursor-pos=`tabpagenr()-1` deol:zsh<CR>
'''

hook_source = '''
  let g:deol#prompt_pattern = '\w*% '
  let g:deol#shell_history_path = $ZDOTDIR . '/zsh_history'
'''

[plugins.ftplugin]
deol = '''
  nmap <buffer> i      <Plug>(deol_edit)
'''
zsh = '''
  imap <buffer> <C-c>  <Plug>(deol_quit)
'''
