[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'

hook_source = 'lua require("plugins.deoplete").hook_source()'
hook_post_source = 'lua require("plugins.deoplete").hook_post_source()'

# Completion sources
[[plugins]]
repo = 'Shougo/neco-syntax'
depends = ['deoplete.nvim']
on_source = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

# Completion preview window based on neovim's floating window
[[plugins]]
repo = 'ncm2/float-preview.nvim'
on_source = ['deoplete.nvim']
if = 'has("nvim")'
hook_source = '''
  let g:float_preview#docked = 0
  let g:float_preview#max_width = 60
  let g:float_preview#max_height = 20
'''

