# === Plugins (loaded on startup) ===

#==============================================================================
# Fundamentals
#==============================================================================

# Dark powered Vim/Neovim plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Enable configuration file in each directory
[[plugins]]
repo = 'thinca/vim-localrc'

# EditorConfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
if = 'executable("editorconfig")'
hook_add = '''
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*', 'term://.*']
'''

# A wrapper around vim.loop for job management
[[plugins]]
repo = 'TravonteD/luajob'

# #==============================================================================
# # Finder
# #==============================================================================
# [[plugins]]
# repo = 'liuchengxu/vim-clap'
# merged = 0
# hook_add = '''
#   let g:clap_cache_directory = $VIM_CACHE_HOME . '/clap'
#   let g:clap_layout = { 'relative': 'editor' }
#   let g:clap_search_box_border_style = 'curve'
#   let g:clap_enable_icon = 1
#   let g:clap_provider_grep_enable_icon = 1
#
#   nnoremap <silent><Space>b  <cmd>Clap! buffers<CR>
#   nnoremap <silent><Space>f  <cmd>Clap! files<CR>
#   nnoremap <silent><Space>h  <cmd>Clap! help_tags<CR>
#   nnoremap <silent><Space>j  <cmd>Clap! jumps<CR>
#   nnoremap <silent><Space>k  <cmd>Clap! maps<CR>
#   nnoremap <silent><Space>l  <cmd>Clap! loclist<CR>
#   nnoremap <silent><Space>q  <cmd>Clap! quickfix<CR>
#   nnoremap <silent><Space>y  <cmd>Clap! yanks<CR>
#   nnoremap <silent><Space>/  <cmd>Clap! lines<CR>
#   nnoremap <silent><Space>*  <cmd>Clap! lines ++query=<cword><CR>
#   nnoremap <silent><Space>;  <cmd>Clap! command_history<CR>
# '''
# hook_post_update = 'Clap install-binary'

#==============================================================================
# Interfaces
#==============================================================================

# Provides the branch name of the current git repository
[[plugins]]
repo = 'itchyny/vim-gitbranch'

# Faster than the built-in 'matchparen' plugin
[[plugins]]
repo = 'itchyny/vim-parenmatch'

# Visually displaying indent levels with thin vertical lines
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_enable = 1
  let g:indentLine_char = '¦'
  " Keep my conceal setting
  let g:indentLine_setConceal = 0
'''

# Better whitespace highlighting for Vim
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
  let g:better_whitespace_enabled = 1
  let g:strip_whitespace_on_save  = 1
  let g:show_spaces_that_precede_tabs = 1
  let g:better_whitespace_filetypes_blacklist = [
      \ 'diff', 'gitcommit', 'defx', 'denite', 'qf', 'help',
      \ 'markdown', 'which_key'
      \ ]
  nnoremap <silent><Leader>x  :<C-u>StripWhitespace<CR>
'''

# Seemless navitation between Tmux and Vim
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
  let g:tmux_navigator_no_mappings = 1
  nnoremap <silent><M-h>  :<C-u>TmuxNavigateLeft<CR>
  nnoremap <silent><M-j>  :<C-u>TmuxNavigateDown<CR>
  nnoremap <silent><M-k>  :<C-u>TmuxNavigateUp<CR>
  nnoremap <silent><M-l>  :<C-u>TmuxNavigateRight<CR>
  nnoremap <silent><M-\>  :<C-u>TmuxNavigatePrevious<CR>

  tnoremap <silent><M-h>  :<C-u>TmuxNavigateLeft<CR>
  tnoremap <silent><M-j>  :<C-u>TmuxNavigateDown<CR>
  tnoremap <silent><M-k>  :<C-u>TmuxNavigateUp<CR>
  tnoremap <silent><M-l>  :<C-u>TmuxNavigateRight<CR>
'''

#==============================================================================
# Plugin dependencies (non-lazy loading)
#==============================================================================

# Find fenced code blocks and filetype (e.g., Javascript blocks inside HTML)
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Operator extension
[[plugins]]
repo = 'kana/vim-operator-user'

# Textobj extension
[[plugins]]
repo = 'kana/vim-textobj-user'

# Powerful repeat '.'
[[plugins]]
repo = 'tpope/vim-repeat'

# Completion srouces
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/deoplete-lsp'
if = 'has("nvim-0.5")'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'

[[plugins]]
repo = 'zchee/deoplete-zsh'

[[plugins]]
repo = 'kristijanhusak/defx-git'

# Denite sources for quickfix, location_list
[[plugins]]
repo = 'chemzqm/unite-location'

#==============================================================================
# Appearance
#==============================================================================

# Iceberg color scheme
# [[plugins]]
# repo = 'cocopon/iceberg.vim'

# # palenight
# [[plugins]]
# repo = 'drewtempelmeyer/palenight.vim'

#==============================================================================
# Syntax, filetype (not necessary for lazy loading)
#==============================================================================

# A collection of language packs for Vim
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disable = ['json', 'markdown']
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# D language
[[plugins]]
repo = 'JesseKPhillips/d.vim'

# Python
[[plugins]]
# extend % and g% for python
repo = 'vim-scripts/python_match.vim'

[[plugins]]
repo = 'raimon49/requirements.txt.vim'

# CSV
[[plugins]]
repo = 'chrisbra/csv.vim'

# Markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
  let g:vim_markdown_conceal = 0
'''
# JSON
[[plugins]]
repo = 'neoclide/jsonc.vim'

# zsh
[[plugins]]
repo = 'chrisbra/vim-zsh'

# GNU As
[[plugins]]
repo = 'Shirk/vim-gas'


