# === Plugins (loaded on startup) ===

#==============================================================================
# Fundamentals
#==============================================================================

# Dark powered Vim/Neovim plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Enable configuration file in each directory
[[plugins]]
repo = 'thinca/vim-localrc'

# EditorConfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
if = 'executable("editorconfig")'
hook_add = '''
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*', 'term://.*']
'''

#==============================================================================
# Interfaces
#==============================================================================

# Provides the branch name of the current git repository
[[plugins]]
repo = 'itchyny/vim-gitbranch'

# Faster than the built-in 'matchparen' plugin
[[plugins]]
repo = 'itchyny/vim-parenmatch'

# Visually displaying indent levels with thin vertical lines
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'lua require("plugins.indentLine").hook_add()'

# # Visually displaying indent levels in Vim.
# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# hook_add = 'lua require("plugins.vim-indent-guides").hook_add()'

# Better whitespace highlighting for Vim
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = 'lua require("plugins.vim-better-whitespace").hook_add()'

# Seemless navitation between Tmux and Vim
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = 'lua require("plugins.vim-tmux-navigator").hook_add()'

#==============================================================================
# Plugin dependencies (non-lazy loading)
#==============================================================================

# Find fenced code blocks and filetype (e.g., Javascript blocks inside HTML)
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Operator extension
[[plugins]]
repo = 'kana/vim-operator-user'

# Textobj extension
[[plugins]]
repo = 'kana/vim-textobj-user'

# Powerful repeat '.'
[[plugins]]
repo = 'tpope/vim-repeat'

# Completion srouces
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/deoplete-lsp'
if = 'has("nvim-0.5")'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'

[[plugins]]
repo = 'zchee/deoplete-zsh'

[[plugins]]
repo = 'kristijanhusak/defx-git'

# Denite sources for quickfix, location_list
[[plugins]]
repo = 'chemzqm/unite-location'

# Plugin library by Google
[[plugins]]
repo = 'google/vim-maktaba'
on_soruce = ['vim-codefmt']

[[plugins]]
repo = 'google/vim-glaive'
on_cmd = ['Glaive']


#==============================================================================
# Appearance
#==============================================================================

# Iceberg color scheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

# Gruvbox with Material Palette
[[plugins]]
repo = 'sainnhe/gruvbox-material'

# Forest Night
[[plugins]]
repo = 'sainnhe/forest-night'

# Edge
[[plugins]]
repo = 'sainnhe/edge'

# Sonokai
[[plugins]]
repo = 'sainnhe/sonokai'

#==============================================================================
# Syntax, filetype (not necessary for lazy loading)
#==============================================================================

# A collection of language packs for Vim
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = 'lua require("plugins.vim-polyglot").hook_add()'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# D language
[[plugins]]
repo = 'JesseKPhillips/d.vim'

# Python
[[plugins]]
# extend % and g% for python
repo = 'vim-scripts/python_match.vim'

[[plugins]]
repo = 'raimon49/requirements.txt.vim'

# CSV
[[plugins]]
repo = 'chrisbra/csv.vim'

# Markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = 'lua require("plugins.vim-markdown").hook_add()'

# JSON
[[plugins]]
repo = 'neoclide/jsonc.vim'

# zsh
[[plugins]]
repo = 'chrisbra/vim-zsh'

# GNU As
[[plugins]]
repo = 'Shirk/vim-gas'


