#-----------------------------------------------------------------------------
# Asyncronous execution
#------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif executable('gmake')
    let cmd =
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

#------------------------------------------------------------------------------
# Auto completion
#------------------------------------------------------------------------------
[[plugins]]
repo             = 'Shougo/deoplete.nvim'
depends          = 'context_filetype.vim'
on_event         = 'InsertEnter'
hook_source      = 'call rc#plugin#deoplete#hook_source()'
hook_post_source = 'call rc#plugin#deoplete#hook_post_source()'

# --- Deoplete sources
[[plugins]]
repo  = 'Shougo/neoinclude.vim'
on_if = 1

#------------------------------------------------------------------------------
# Snippets
#------------------------------------------------------------------------------
[[plugins]]
repo        = 'Shougo/neosnippet'
depends     = ['neosnippet-snippets', 'context_filetype.vim']
on_event    = 'InsertCharPre'
on_ft       = 'snippet'
hook_add    = 'call rc#plugin#neosnippet#hook_add()'
hook_source = 'call rc#plugin#neosnippet#hook_source()'

#------------------------------------------------------------------------------
# Denite
#------------------------------------------------------------------------------
[[plugins]]
repo        = 'Shougo/echodoc.vim'
on_event    = 'CompleteDone'
hook_source = 'call echodoc#enable()'

[[plugins]]
repo        = 'Shougo/denite.nvim'
depends     = ['vim-qfreplace']
on_cmd      = 'Denite'
hook_add    = 'call rc#plugin#denite#hook_add()'
hook_source = 'call rc#plugin#denite#hook_source()'

# --- Denite sources
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = 'denite.nvim'

[[plugins]]
repo      = 'Shougo/neoyank.vim'
on_if     = 1
on_event  = 'TextYankPost'
on_source = 'denite.nvim'

[[plugins]]
repo      = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'

#-----------------------------------------------------------------------------
# Replace grep/quickfix results
#-----------------------------------------------------------------------------
[[plugins]]
repo        = 'thinca/vim-qfreplace'
on_ft       = ['denite', 'qf']
hook_source = '''
  autocmd MyVimrc FileType qf nnoremap <buffer> r :<C-u>Qfreplace<CR>
'''

#-----------------------------------------------------------------------------
# Cursor moves
#-----------------------------------------------------------------------------
[[plugins]]
repo     = 'rhysd/accelerated-jk'
on_map   = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo        = 'easymotion/vim-easymotion'
on_map      = '<Plug>'
on_func     = ['EasyMotion#go']
hook_add    = 'call rc#plugin#easymotion#hook_add()'
hook_source = 'call rc#plugin#easymotion#hook_source()'

#-----------------------------------------------------------------------------
# Editting
#-----------------------------------------------------------------------------
# --- Surround
# [[plugins]]
# repo     = 'rhysd/vim-operator-surround'
# depends  = 'vim-operator-user'
# on_map   = {n = '<Plug>'}
# hook_add = '''
#   nmap <silent>sa <Plug>(operator-surround-append)a
#   nmap <silent>sd <Plug>(operator-surround-delete)a
#   nmap <silent>sr <Plug>(operator-surround-replace)a
#   nmap <silent>sc <Plug>(operator-surround-replace)a
# '''

# vim-sandwich
[[plugins]]
repo        = 'machakann/vim-sandwich'
on_map      = {nxo = '<Plug>'}
on_event    = ['BufRead', 'BufNewFile']
hook_source = '''
  let g:textobj#sandwich#stimeoutlen = 100
  let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
  let g:sandwich#recipes += [{'buns' : ['「', '」']}]
  let g:sandwich#recipes += [{'buns' : ['【', '】']}]
  let g:sandwich#recipes += [{'buns' : ['（', '）']}]
  let g:sandwich#recipes += [{'buns' : ['『', '』']}]
'''

# --- Smart commenter
[[plugins]]
repo     = 'tyru/caw.vim'
on_map   = {nx = '<Plug>'}
hook_add = '''
  function! InitCaw() abort
    if !&l:modifiable
      silent! nunmap <buffer> gc
      silent! xunmap <buffer> gc
      silent! nunmap <buffer> gcc
      silent! xunmap <buffer> gcc
    else
      nmap <buffer> gc <Plug>(caw:prefix)
      xmap <buffer> gc <Plug>(caw:prefix)
      nmap <buffer> gcc <Plug>(caw:hatpos:toggle)
      xmap <buffer> gcc <Plug>(caw:hatpos:toggle)
    endif
  endfunction
  autocmd MyVimrc FileType * call InitCaw()
  call InitCaw()
'''

# --- Smart Align
[[plugins]]
repo     = 'junegunn/vim-easy-align'
on_cmd   = ['EasyAlign', 'LiveEasyAlign']
hook_add = '''
  vnoremap <Enter> :EasyAlign<CR>
'''

# --- SKK imput method for Japanese
[[plugins]]
repo        = 'tyru/eskk.vim'
on_map      = {ic = '<Plug>'}
hook_add    = 'call rc#plugin#eskk#hook_add()'
hook_source = 'call rc#plugin#eskk#hook_source()'

#-----------------------------------------------------------------------------
# Filetype, syntax and more
#-----------------------------------------------------------------------------
# --- Git operations
[[plugins]]
repo             = 'lambdalisue/gina.vim'
on_cmd           = 'Gina'
hook_add         = 'call rc#plugin#gina#hook_add()'
hook_post_source = 'call rc#plugin#gina#hook_post_source()'

# --- reStructuredText (rst)
[[plugins]]
repo  = 'gu-fan/riv.vim'
on_ft = 'rst'

# --- Python pyenv
[[plugins]]
repo  = 'lambdalisue/vim-pyenv'
on_ft = 'python'
# Do not load vim-pyenv until *.py is opened and make sure that it is loaded
# after jedi-vim is loaded.
# depends = 'jedi-vim'

# --- Language server protocol (LSP) client
[[plugins]]
repo        = 'autozimu/LanguageClient-neovim'
depends     = ['deoplete.nvim', 'denite.nvim']
rev         = 'next'
build       = 'bash install.sh'
on_ft       = ['c', 'cpp', 'python', 'rust']
hook_source = 'call rc#plugin#LanguageClient#hook_source()'

# --- Latex
[[plugins]]
repo    = 'lervag/vimtex'
depends = ['deoplete.nvim']
on_ft   = 'tex'
hook_source = 'call rc#plugin#vimtex#hook_source()'

# --- Markdown preview
[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_ft = 'markdown'
depends = ['markdown-preview.vim']

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = 'markdown'
hook_source = '''
  let g:mkdp_refresh_slow = 1
'''

# [[plugins]]
# repo = 'euclio/vim-markdown-composer'
# on_ft = 'markdown'
# hook_post_update = '''
#   if has('nvim')
#     !cargo build --release
#   else
#     !cargo build --release --no-default-features --features json-rpc
#   endif
# '''

#------------------------------------------------------------------------------
# Leader guide
#------------------------------------------------------------------------------
# repo = 'hecal3/vim-leader-guide'
# on_event = ['VimEnter']
# hook_post_source = '''
#   let g:topdict = {}
#   let g:topdict[' '] = g:lmap
#   let g:topdict[' ']['name'] = '<leader>'
#   let g:topdict[','] = g:llmap
#   let g:topdict[',']['name'] = '<localleader>'
#
#   " register it with the guide:
#   call leaderGuide#register_prefix_descriptions("", "g:topdict")
#
#   " define mappings:
#   nnoremap <silent> <Leader>  :<C-u>LeaderGuide       '<Space>'<CR>
#   vnoremap <silent> <Leader>  :<C-u>LeaderGuideVisual '<Space>'<CR>
#   map               <Leader>.  <Plug>leaderguide-global
#   nnoremap <LocalLeader>      :<C-u>LeaderGuide        ','<CR>
#   vnoremap <LocalLeader>      :<C-u>LeaderGuideVisual  ','<CR>
#   map      <LocalLeader>.      <Plug>leaderguide-buffer<Paste>
# '''

