 # === Plugins (lazy loading) ===

#------------------------------------------------------------------------------
# Denite
#------------------------------------------------------------------------------
# Dark powered asynchronous unite all interfaces for Neovim/Vim8
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['vim-qfreplace']
on_cmd = 'Denite'
hook_add = 'call rc#plugin#denite#hook_add()'
hook_source = 'call rc#plugin#denite#hook_source()'

# Freaky fast fuzzy Denite/CrtlP matcher for vim/neovim
[[plugins]]
repo = 'raghur/fruzzy'
on_source = ['denite.nvim']
hook_source = '''
  let g:fruzzy#usenative = 1
  let g:fruzzy#sortonempty = 0
'''
hook_post_update = 'call fruzzy#install()'

# Denite plugin for temporary files
[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'denite.nvim'
hook_source = '''
  let g:junkfile#directory = $VIM_CACHE_HOME . '/junkfile'
'''

# Denite plugin for MRU
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'

# Denite plugin for yank history
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = 'denite.nvim'

# Denite location andd quickfix lists
[[plugins]]
repo = 'chemzqm/unite-location'
on_source = 'denite.nvim'

# Denite source for ghq list
[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'

# Browse and open sesions
[[plugins]]
repo = 'rafi/vim-denite-session'
on_source = 'denite.nvim'
hook_source = '''
  let g:session_directory = $VIM_CACHE_HOME . '/session'
'''

#------------------------------------------------------------------------------
# Auto completion
#------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['context_filetype.vim']
on_event = 'InsertEnter'
hook_source = 'call rc#plugin#deoplete#hook_source()'
hook_post_source = 'call rc#plugin#deoplete#hook_post_source()'

# --- Deoplete sources
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

# --- Source for Vim script
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

# --- Auto close parentheses
[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:lexima_ctrlh_as_backspace = 1
'''
hook_post_source = '''
  " call lexima#add_rule({'char': '<C-h>', 'at': '(\%#)',   'delete': 1})
  " call lexima#add_rule({'char': '<C-h>', 'at': '{\%#}',   'delete': 1})
  " call lexima#add_rule({'char': '<C-h>', 'at': '\[\%#\]', 'delete': 1})
  " call lexima#add_rule({'char': '<C-h>', 'at': '"\%#"',   'delete': 1})
  " call lexima#add_rule({'char': '<C-h>', 'at': "'\\%#'",  'delete': 1})
  " call lexima#add_rule({'char': '<C-h>', 'at': '`\%#`',   'delete': 1})

  call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': 'latex'})
  call lexima#add_rule({'char': '$', 'at': '\%#\$', 'leave': 1, 'filetype': 'latex'})
  call lexima#add_rule({'char': '<BS>',  'at': '\$\%#\$', 'delete': 1, 'filetype': 'latex'})
  " call lexima#add_rule({'char': '<C-h>', 'at': '\$\%#\$', 'delete': 1, 'filetype': 'latex'})
'''

#------------------------------------------------------------------------------
# Snippets
#------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
  imap <silent><C-s>  <Plug>(neosnippet_expand_or_jump)
  smap <silent><C-s>  <Plug>(neosnippet_expand_or_jump)
  xmap <silent><C-s>  <Plug>(neosnippet_expand_target)

  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#expand_word_boundary = 1
  let g:neosnippet#snippets_directory = g:vimrc_root . '/snippets'

  autocmd MyVimrc CompleteDone * call neosnippet#complete_done()
'''

#-----------------------------------------------------------------------------
# Commands
#-----------------------------------------------------------------------------
# Dark ppowered file explorer implementation
[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = ['Defx']
hook_add = '''
  nnoremap <silent><Leader>f  :<C-u>Defx<CR>
'''
hook_source = 'call rc#plugin#defx#hook_source()'

# Git status implementation for Defx
[[plugins]]
repo = 'kristijanhusak/defx-git'
on_source = 'defx.nvim'

# Filetype icons for Defx
[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_source = 'defx.nvim'

# Perform the replacement in |quickfix|
[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['qf']
[plugins.ftplugin]
qf = '''
  nnoremap <buffer> R :<C-u>Qfreplace<CR>
'''

# Navigate windows like tmux's 'display-pane'
[[plugins]]
repo = 't9md/vim-choosewin'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap -   <Plug>(choosewin)
'''

# The interactive scratchpad for hackers
[[plugins]]
repo = 'metakirby5/codi.vim'
on_cmd = ['Codi']

# Git wrapper
[[plugins]]
repo = 'neoclide/vim-easygit'
on_cmd = ['Gcd', 'Glcd', 'Gblame', 'GcommitCurrent', 'GdiffThis', 'Gcommit',
          'Gedit', 'Gdiff', 'Gremove', 'Grename', 'Gmove', 'Gcheckout',
          'Gpush', 'Gpull', 'Gfetch', 'Gadd', 'Gstatus', 'Ggrep', 'Gmerge']
hook_source = '''
  let g:easygit_enable_command = 1
'''

# Git operations
[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
hook_add = 'call rc#plugin#gina#hook_add()'
hook_post_source = 'call rc#plugin#gina#hook_post_source()'

# --- Smart Align
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = ['EasyAlign', 'LiveEasyAlign']
hook_add = '''
  vnoremap <Enter> :EasyAlign<CR>
'''
on_map = {x = '<Plug>'}

# # --- Neoterm
# repo = 'kassio/neoterm'
# on_cmd = ['T', 'Texe', 'Tnew', 'Tclear', 'Tkill', 'Tmap', 'Tpos',
#           'TREPLSetTerm', 'TREPLSendFile', 'TREPLSendLine', 'TREPLSendSelection',
#           'Topen', 'Tclose', 'TcloseAll', 'Ttoggle', 'TtoggleAll', 'Tnext', 'Tprevious']
# hook_add = '''
#   let g:neoterm_autoscroll = 1
#   nnoremap [Term] <Nop>
#   nmap     <Leader>T [Term]
#
#   nnoremap [Term]n  :Tnew<CR>
#   nnoremap [Term]v  :vertical Tnew<CR>
#   " 3<leader>Tl will clear neoterm-3.
#   nnoremap [Term]l  :<C-u>exec v:count.'Tclear'<CR>
#
#   " REPL operators (work with textobj)
#   nmap gx  <Plug>(neoterm-repl-send)
#   " Send section to REPL
#   xmap gx  <Plug>(neoterm-repl-send)
#   " Send the current line to REPL
#   nmap gxx <Plug>(neoterm-repl-line)
# '''

#----------------------------------------------------------------------------et-
# Interfaces
#-----------------------------------------------------------------------------
# SKK imput method for Japanese
[[plugins]]
repo = 'tyru/eskk.vim'
on_map = {ic = '<Plug>'}
hook_add = 'call rc#plugin#eskk#hook_add()'
hook_source = 'call rc#plugin#eskk#hook_source()'

# Make blockwise visual mode more useful
[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {n = '<Plug>'}

# Vim motions on speed!
[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = {n = '<Plug>'}
hook_add = 'call rc#plugin#easymotion#hook_add()'
hook_source = 'call rc#plugin#easymotion#hook_source()'

# Move to the edge!
[[plugins]]
repo = 'haya14busa/vim-edgemotion'
on_map = {nv = '<Plug>'}
hook_add = '''
  map  <C-j>  <Plug>(edgemotion-j)
  map  <C-k>  <Plug>(edgemotion-k)
  xmap <C-j>  <Plug>(edgemotion-j)
  xmap <C-k>  <Plug>(edgemotion-k)
'''

# Accerlerate up-down moving!
[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

#  Extended J command
[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = {nx = '<Plug>'}
hook_add = '''
  nmap J  <Plug>(jplus)
  vmap J  <Plug>(jplus)

  " Insert one or more characters when join
  nmap <Leader>J  <Plug>(jplus-input)
  vmap <Leader>J  <Plug>(jplus-input)
'''

# Quickly highlight <cword> or visually selected word
[[plugins]]
repo   = 't9md/vim-quickhl'
on_map = {nv = '<Plug>'}
hook_add = '''
  " TODO: key mapping conflict
  nmap <Leader>, <Plug>(quickhl-manual-this)
  xmap <Leader>, <Plug>(quickhl-manual-this)
'''

# Smart commenter
[[plugins]]
repo = 'tyru/caw.vim'
on_map = {nv = '<Plug>'}
hook_add = '''
  let g:caw_no_default_keymappings = 1

  nmap <Leader>c   <Plug>(caw:prefix)
  xmap <Leader>c   <Plug>(caw:prefix)
  nmap <Leader>cc  <Plug>(caw:hatpos:toggle)
  xmap <Leader>cc  <Plug>(caw:hatpos:toggle)
  nmap <Leader>ca  <Plug>(caw:dollarpos:toggle)
  xmap <Leader>ca  <Plug>(caw:dollarpos:toggle)
  nmap <Leader>cb  <Plug>(caw:box:toggle)
  xmap <Leader>cb  <Plug>(caw:box:toggle)
  nmap <Leader>cw  <Plug>(caw:wrap:toggle)
  xmap <Leader>cw  <Plug>(caw:wrap:toggle)
  nmap <Leader>co  <Plug>(caw:jump:comment-next)
  nmap <Leader>cO  <Plug>(caw:jump:comment-prev)
'''


# Calendar
[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = 'Calendar'
hook_source = '''
  let g:calendar_google_calendar = 1
  let g:calendar_google_task = 1
'''

# Show a git diff in the gutter and stages/undoes hunks
[[plugins]]
repo = 'airblade/vim-gitgutter'
if = 'has("signs")'
on_path = '.*'

# More pleasant editing on commit messages
[[plugins]]
repo = 'rhysd/committia.vim'
on_path = 'COMMIT_EDITMSG'
hook_source = '''
  let g:committia_min_window_width = 100
'''
# Visually displaying indent levels in code
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_cmd = ['IndentGuidesEnable', 'IndentGuidesDisable', 'IndentGuidesToggle']
hook_add = '''
  nmap <silent><Leader>ti :<C-u>IndentGuidesToggle<CR>
'''
hook_source = '''
  let g:indent_guides_enable_on_vim_startup = 0
  let g:indent_guides_default_mapping = 0
  let g:indent_guides_indent_levels = 15
  let g:indent_guides_start_level = 2
  let g:indent_guides_exclude_filetypes = ['help', 'denite', 'codi']
  let g:indend_guides_color_change_percent = 20
'''

#------------------------------------------------------------------------------
# Textobj/Operator extensions
#------------------------------------------------------------------------------
[[plugins]]
repo = 'machakann/vim-sandwich'
#on_map = {nxo = '<Plug>'}
on_path = '.*'
hook_add = 'call rc#plugin#sandwich#hook_add()'
hook_source = 'call rc#plugin#sandwich#hook_source()'

[[plugins]]
repo = 'kana/vim-textobj-line'
depends = ['vim-textobj-user']
on_func = 'textobj#user#'

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = ['vim-textobj-user']
on_map = {nx = '<Plug>'}

[[plugins]]
repo = 'machakann/vim-textobj-delimited'
on_map = {ox = '<Plug>'}
hook_add = '''
  let g:textobj_delimited_no_default_key_mappings = 1

  xmap id  <Plug>(textobj-delimited-forward-i)
  omap id  <Plug>(textobj-delimited-forward-i)

  xmap ad  <Plug>(textobj-delimited-forward-a)
  omap ad  <Plug>(textobj-delimited-forward-a)

  xmap iD  <Plug>(textobj-delimited-backward-i)
  omap iD  <Plug>(textobj-delimited-backward-i)

  xmap aD  <Plug>(textobj-delimited-backward-a)
  omap aD  <Plug>(textobj-delimited-backward-a)
'''

# # --- Move function arguments left and right
# [[plugins]]
# repo = 'AndrewRadev/sideways.vim'
# on_map = {ox = '<Plug>Sideways'}
# hook_add = '''
#   " nnoremap <silent>sh   :<C-u>SidewaysLeft<CR>
#   " nnoremap <silent>sl   :<C-u>SidewaysRight<CR>
#
#   omap <silent> a,  <Plug>SidewaysArgumentTextobjA
#   xmap <silent> a,  <Plug>SidewaysArgumentTextobjA
#   omap <silent> i,  <Plug>SidewaysArgumentTextobjI
#   xmap <silent> i,  <Plug>SidewaysArgumentTextobjI
# '''

# --- Expand region
[[plugins]]
repo = 'terryma/vim-expand-region'
depends = ['vim-sandwich', 'vim-textobj-delimited']
on_map = {x = '<Plug>'}
hook_add = '''
  "ad: textobj-delimeted"
  "ib: sandwich"
  let g:expand_region_text_objects = {
        \ 'iw'  : 0,
        \ 'iW'  : 0,
        \ 'iu'  : 0,
        \ 'ad'  : 1,
        \ 'ib'  : 1,
        \ 'il'  : 0,
        \ 'ip'  : 0,
        \ 'ie'  : 0,
        \ }

  xmap v  <Plug>(expand_region_expand)
  xmap V  <Plug>(expand_region_shrink)
'''

#-----------------------------------------------------------------------------
# Language, Filetypes
#-----------------------------------------------------------------------------
# --- Print document on echo area
[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = 'call echodoc#enable()'

# --- Asynchronous Lint Engine (ALE)
[[plugins]]
repo = 'w0rp/ale'
on_path = '.*'
hook_add = 'call rc#plugin#ale#hook_add()'
hook_source = 'call rc#plugin#ale#hook_source()'

# --- Language server protocol (LSP) client
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
depends = ['deoplete.nvim', 'denite.nvim']
rev = 'next'
build = 'bash install.sh'
on_ft = ['c', 'cpp', 'python', 'rust', 'sh']
hook_source = 'call rc#plugin#LanguageClient#hook_source()'

# --- LaTeX
[[plugins]]
repo = 'lervag/vimtex'
depends = ['deoplete.nvim']
on_ft = 'tex'
hook_source = 'call rc#plugin#vimtex#hook_source()'

# --- Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
# hook_source = '''
#   let g:rustfmt_autosave = 1
# '''

# --- Python
[[plugins]]
repo = 'plytophogy/vim-virtualenv'
on_ft = 'python'
on_source = '''
  let g:virtualenv_directory = $PYENV_ROOT . '/versions'
'''

[[plugins]]
repo = 'tmhedberg/SimpylFold'
on_ft = 'python'

[[plugins]]
repo = 'raimon49/requirements.txt.vim'
on_ft = 'requirements'

# --- HTML/CSS/Javascript
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'jsx', 'javascript', 'javascript.jsx']

# --- CSV
[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = 'csv'

# --- Markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
  let g:vim_markdown_conceal = 0
'''

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = 'markdown'

# Generate table of contents for Markdown file
[[plugins]]
repo = 'mzlogin/vim-markdown-toc'
on_cmd = ['GenTocGFM', 'GenTocRedcarpet', 'GenTocGitLab', 'UpdateToc']
hook_source = '''
  let g:vmt_auto_update_on_save = 0
'''

# Markdown live preview
[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_ft = 'markdown'
depends = ['markdown-preview.vim']

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = 'markdown'
hook_source = '''
  let g:mkdp_refresh_slow = 1
'''

# --- Emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'jsx', 'javascript', 'javascript.jsx']

# --- Hex editor
[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'
hook_add = '''
  let g:vinarise_enable_auto_detect = 1
'''

