# === Plugins (loaded on startup) ===

#------------------------------------------------------------------------------
# Plugin manager
#------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  nnoremap <silent> <Leader>Du :<C-u>call dein#clear_state()<CR>:UpdateRemotePlugins<CR>
  nnoremap <silent> <Leader>DU :<C-u>call dein#update()<CR>
'''

#------------------------------------------------------------------------------
# Functions and commands for Neovim GUI
#------------------------------------------------------------------------------
[[plugins]]
repo = 'equalsraf/neovim-gui-shim'
if = 'has("nvim")'

#------------------------------------------------------------------------------
# Remote Plugin Framework
#------------------------------------------------------------------------------
# for Vim 8
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

[[plugins]]
repo = 'https://github.com/roxma/nvim-yarp'

#------------------------------------------------------------------------------
# Fast matcher for CtrlP and Denite
#------------------------------------------------------------------------------
[[plugins]]
repo = 'nixprime/cpsm'
build = 'sh -c "PY3=ON ./install.sh"'

#------------------------------------------------------------------------------
# Utilities
#------------------------------------------------------------------------------
# Enable configuration file in each directory
[[plugins]]
repo = 'thinca/vim-localrc'

# # Faster than the built-in 'matchparen' plugin
# [[plugins]]
# repo = 'itchyny/vim-parenmatch'

# [[plugins]]
# repo     = 'itchyny/vim-cursorword'
# hook_add = '''
#   augroup cursorword-filetype
#     autocmd!
#     autocmd FileType qf,denite,unite,vimfiler,quickrun,calendar let b:cursorword = 0
#     autocmd InsertEnter * let b:cursorword = 0
#     autocmd InsertLeave * let b:cursorword = 1
#   augroup END
# '''

# Powerful repeat '.'
[[plugins]]
repo = 'tpope/vim-repeat'

# --- EditorConfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
if = 'executable("editorconfig")'
hook_add = '''
  let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
'''

#------------------------------------------------------------------------------
# Lightline + Colorscheme
#------------------------------------------------------------------------------
# Custom status line
[[plugins]]
repo = 'itchyny/lightline.vim'

# Add filetype glyphs (icons) to other plugins
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# Create tmux powerline theme from vim powerline theme
# (requires powerline/vim-airline/lightline)
[[plugins]]
repo = 'edkolev/tmuxline.vim'

#  Dracula
[[plugins]]
repo = 'dracula/vim'
name = 'dracula'

#  Iceberg -- with lightline colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

#  gruvbox -- truecolor support with lightline colorscheme
[[plugins]]
repo = 'morhetz/gruvbox'

#  tender -- truecolor support with lightline colorscheme
[[plugins]]
repo = 'jacoborus/tender.vim'

#  onedark -- truecolor support with lightline colorscheme
[[plugins]]
repo = 'joshdick/onedark.vim'

#  neodark -- truecolor support with lightline colorscheme
[[plugins]]
repo = 'KeitaNakamura/neodark.vim'

#  PaperColor -- truecolor / GUI-color and 256-color support
[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

#------------------------------------------------------------------------------
# Vim help in Japanese
#------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja,en'

# Introduction of VIM script
[[plugins]]
repo = 'mattn/learn-vimscript'

#------------------------------------------------------------------------------
# Plugins for completion
#------------------------------------------------------------------------------
# --- Snippet definitions for neosnippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# --- Completion by `look` command for neocomplete/deoplete/ncm
[[plugins]]
repo = 'ujihisa/neco-look'
if = 'executable("look")'

# --- syntax source for neocomplete/deoplete/ncm
[[plugins]]
repo = 'Shougo/neco-syntax'

# === No meaning lazy plugins ===

# --- Textobj extension
  [[plugins]]
repo = 'kana/vim-textobj-user'

# --- Operator extension
[[plugins]]
repo = 'kana/vim-operator-user'

# --- Find fenced code blocks and filetype
#     (e.g., Javascript blocks inside HTML)
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# --- C++
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'

# --- Python
[[plugins]]
repo = 'vim-python/python-syntax'

[[plugins]]
# extend % and g% for python
repo = 'vim-scripts/python_match.vim'

# --- diff
[[plugins]]
repo = 'thinca/vim-ft-diff_fold'

# --- help
[[plugins]]
repo = 'thinca/vim-ft-help_fold'

# --- CSS
[[plugins]]
repo = 'hail2u/vim-css3-syntax'

# --- JSON
[[plugins]]
repo = 'elzr/vim-json'

# --- YAML
[[plugins]]
repo = 'stephpy/vim-yaml'

# --- TOML
[[plugins]]
repo = 'cespare/vim-toml'

# --- Docker files
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

# --- fish
[[plugins]]
repo = 'kballard/vim-fish'

# --- zsh
[[plugins]]
repo = 'chrisbra/vim-zsh'

# --- GNU As
[[plugins]]
repo = 'Shirk/vim-gas'

# --- tmux
[[plugins]]
repo = 'tmux-plugins/vim-tmux'

# --- vim
[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

