# Global hook_add, which is executed in dein#end(). {{{
# -----
hook_add = '''
  " -- C++
  let g:cpp_class_scope_highlight = 1

  " -- Python
  let g:python_highlight_all = 1

  " -- Ruby
  let g:ruby_fold = 1

  " -- perl
  let g:perl_fold = 1
  let g:perl_fold_blocks = 1

  " -- php
  let g:php_folding = 1

  " -- Vim
  let g:vimsyntax_noerror = 1
  let g:vimsyn_folding = 'af'

  " -- Bash
  let g:is_bash = 1
  let g:sh_fold_enabled = 7

  " -- Markdown
  let g:markdown_fenced_languages = [
    \ 'css',
    \ 'javascript',
    \ 'js=javascript',
    \ 'json=javascript',
    \ 'python',
    \ 'py=python',
    \ 'sh',
    \ 'sass',
    \ 'xml',
    \ 'vim'
    \ ]

  " -- LaTeX
  let g:tex_stylish = 1
  let g:tex_conceal = ''
  let g:tex_flavor = 'latex'
  let g:tex_isk='48-57,a-z,A-Z,192-255,:'
  let g:tex_fold_enabled = 1

  " -- XML
  let g:xml_syntax_folding = 1
'''
# }}}

# Hooks on filetypes {{{
[ftplugin]
# NOTE: '_' key is executed after all ftplugin {{{
_ = '''
  " Disable automatically insert comment.
  setlocal formatoptions-=ro | setlocal formatoptions+=mMBl

  " Disable auto wrap.
  if &l:textwidth != 70 && &filetype !=# 'help'
    setlocal textwidth=0
  endif

  if !&l:modifiable
    setlocal nofoldenable
    setlocal foldcolumn=0
    if v:version >= 703
      setlocal colorcolumn=
    endif
  endif
'''
# }}}

# C++
cpp = '''
  setlocal foldignore=#/
'''

# Ruby
ruby = '''
  setlocal iskeyword+=!
  setlocal iskeyword+=?
  setlocal omnifunc=
'''

# TOML
toml = '''
  syntax sync minlines=500
'''

# VIM script
vim = '''
  if 5000 < line('$')
    syntax sync minlines=200
  endif
  setlocal foldmethod=indent
'''

# VIM help
help = '''
  setlocal iskeyword+=:
  setlocal iskeyword+=#
  setlocal iskeyword+=-
'''

# }}}

#-----------------------------------------------------------------------------
# vim: foldmethod=marker
