# === Plugins (lazy loading) ===

# --- Auto completion {{{

# Tag/include sources for neocomlete/deoplete/ncm2
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

# Vim source for neocomplete/deoplete
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

# Auto close parentheses
[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:lexima_ctrlh_as_backspace = 1
'''
hook_post_source = ''' "{{{
  call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': 'latex'})
  call lexima#add_rule({'char': '$', 'at': '\%#\$', 'leave': 1, 'filetype': 'latex'})
  call lexima#add_rule({'char': '<BS>', 'at': '\$\%#\$', 'delete': 1, 'filetype': 'latex'})
"}}} '''

# Auto create TAG files
[[plugins]]
repo = 'ludovicchabant/vim-gutentags'
if = "executable('ctags')"
on_path = '.*'
hook_add = ''' "{{{
  let g:gutentags_cache_dir           = $VIM_CACHE_HOME . '/tags'
  let g:gutentags_generate_on_missing = 0
  let g:gutentags_generate_on_new     = 0
  let g:gutentags_generate_on_save    = 1
  let g:gutentags_exclude_filetype    = []
  let g:gutentags_ctags_exclude_wildignore = 1
  let g:gutentags_ctags_exclude = [
        \ '*/build', '*/wp-admin', '*/wp-content', '*/wp-includes',
        \ '*/application/vendor', '*/vendor/ckeditor', '*/media/vendor'
        \ ]
"}}} '''

# --- }}}

# --- Commands {{{

# Utility commands for dein.vim
[[plugins]]
repo = 'haya14busa/dein-command.vim'
depends = ['dein.vim']
on_cmd = ['Dein']

# View and search LSP symbols and tags in Vim/NeoVim
[[plugins]]
repo = 'liuchengxu/vista.vim'
depends = ['coc.nvim', 'lightline.vim']
on_cmd = ['Vista', 'Vista!', 'Vista!!']
hook_add = '''
  " toggle vista view window
  nnoremap <silent> <Space>v  :<C-u>Vista!!<CR>

  let g:vista_default_executive = 'ctags'
  let g:vista_executive_for = {
       \ 'c':          'coc',
       \ 'cpp':        'coc',
       \ 'fortran':    'coc',
       \ 'go':         'coc',
       \ 'java':       'coc',
       \ 'javascript': 'coc',
       \ 'json':       'coc',
       \ 'python':     'coc',
       \ 'ruby':       'coc',
       \ 'rust':       'coc',
       \ 'yaml':       'coc',
       \ }
'''


# Defx --- Dark ppowered file explorer implementation
[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = ['Defx']
hook_add = '''
  nnoremap <silent><Space>d  :<C-u>Defx<CR>
'''
hook_source = ''' "{{{
  call defx#custom#option('_', {
        \ 'columns': 'icons:git:filename:type',
        \ 'winwidth': 30,
        \ 'split': 'vertical',
        \ 'direction': 'topleft'
        \ })
  call defx#custom#column('mark', {
        \ 'directory_icon': '▸',
        \ 'readonly_icon': '✗',
        \ 'selected_icon': '✓',
        \ })
"}}} '''
[plugins.ftplugin]
defx = ''' "{{{
  " Define mappings
  nnoremap <silent><buffer><expr> <CR> defx#async_action('drop')
  nnoremap <silent><buffer><expr> c    defx#do_action('copy')
  nnoremap <silent><buffer><expr> !    defx#do_action('execute_command')
  nnoremap <silent><buffer><expr> m    defx#do_action('move')
  nnoremap <silent><buffer><expr> p    defx#do_action('paste')
  nnoremap <silent><buffer><expr> l    defx#async_action('open')
  nnoremap <silent><buffer><expr> E    defx#do_action('open', 'vsplit')
  nnoremap <silent><buffer><expr> P    defx#do_action('open', 'pedit')
  nnoremap <silent><buffer><expr> K    defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> N    defx#do_action('new_file')
  nnoremap <silent><buffer><expr> M    defx#do_action('new_multiple_files')
  nnoremap <silent><buffer><expr> C    defx#do_action('toggle_columns', 'mark:filename:type:size:time')
  nnoremap <silent><buffer><expr> S    defx#do_action('toggle_sort', 'Time')
  nnoremap <silent><buffer><expr> d    defx#do_action('remove_trash')
  nnoremap <silent><buffer><expr> r    defx#do_action('rename')
  nnoremap <silent><buffer><expr> x    defx#do_action('execute_system')
  nnoremap <silent><buffer><expr> >    defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> .    defx#do_action('repeat')
  nnoremap <silent><buffer><expr> yy   defx#do_action('yank_path')
  nnoremap <silent><buffer><expr> h    defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> ~    defx#do_action('cd')
  nnoremap <silent><buffer><expr> \    defx#do_action('cd', getcwd())
  nnoremap <silent><buffer><expr> q    defx#do_action('quit')
  nnoremap <silent><buffer><expr> <Space> defx#do_action('toggle_select') . 'j'
  xnoremap <silent><buffer><expr> <CR> defx#do_action('toggle_select_visual')
  nnoremap <silent><buffer><expr> *    defx#do_action('toggle_select_all')
  nnoremap <silent><buffer><expr> j    line('.') == line('$') ? 'gg' : 'j'
  nnoremap <silent><buffer><expr> k    line('.') == 1 ? 'G' : 'k'
  nnoremap <silent><buffer><expr> <C-l> defx#do_action('redraw')
  nnoremap <silent><buffer><expr> <C-g> defx#do_action('print')
  nnoremap <silent><buffer><expr> <Tab> winnr('$') != 1 ?
        \ ':<C-u>wincmd w<CR>' :
        \ ':<C-u>Defx -buffer-name=temp -split=vertical<CR>'
"}}} '''

# --- Defx extensions
# Git status implementation for Defx
[[plugins]]
repo = 'kristijanhusak/defx-git'
on_source = 'defx.nvim'

# Filetype icons for Defx
[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_source = 'defx.nvim'

# Perform the replacement in |quickfix|
[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['qf']
[plugins.ftplugin]
qf = '''
  nnoremap <buffer> R :<C-u>Qfreplace<CR>
'''

# Navigate windows like tmux's 'display-pane'
[[plugins]]
repo = 't9md/vim-choosewin'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap -  <Plug>(choosewin)
'''

# The interactive scratchpad for hackers
[[plugins]]
repo = 'metakirby5/codi.vim'
on_cmd = ['Codi']

# --- Smart Align
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = ['EasyAlign', 'LiveEasyAlign']
on_map = ['<Plug>(EasyAlign)', '<Plug>(LiveEasyAlign)']
hook_add = ''' "{{{
  nmap <silent><Leader>a  <Plug>(EasyAlign)
  vmap <silent><Leader>a  <Plug>(EasyAlign)
"}}} '''

# --- Switch between single-line and multiline forms of code
[[plugins]]
# use default mapping
#   gS -> SplitjoinSplit
#   gJ -> SplitjoinJoin
repo = 'AndrewRadev/splitjoin.vim'
on_map = {n = '<Plug>Splitjoin'}

# --- Displays available keybindingss in pupup
# [[plugins]]
# repo = 'liuchengxu/vim-which-key'
# on_cmd = ['WhichKey', 'WhichKey!', 'WhichKeyVisual', 'WhichKeyVisual!']
# hook_add = ''' "{{{
#   nnoremap <silent> <Space>  :<C-u>WhichKey       '<Space>'<CR>
#   vnoremap <silent> <Space>  :<C-u>WhichKeyVisual '<Space>'<CR>
#   nnoremap <silent> ;        :<C-u>WhichKey       ';'<CR>
#   vnoremap <silent> ;        :<C-u>WhichKeyVisual ';'<CR>
#   nnoremap <silent> ,        :<C-u>WhichKey       ','<CR>
#   vnoremap <silent> ,        :<C-u>WhichKeyVisual ','<CR>
#   nnoremap <silent> s        :<c-u>whichkey       's'<cr>
#   vnoremap <silent> s        :<c-u>whichkeyvisual 's'<cr>
#   nnoremap <silent> m        :<C-u>WhichKey       'm'<CR>
#   vnoremap <silent> m        :<C-u>WhichKeyVisual 'm'<CR>
# "}}} '''
# hook_source = 'source $VIM_CONFIG_HOME/rc/plugins/which_key.vim'
#
[[plugins]]
repo = 'paroxayte/vkmap.vim'
depends = ['vwm.vim']
on_event = 'VimEnter'
hook_source = 'source $VIM_CONFIG_HOME/rc/plugins/vkmap.vim'

[plugins.ftplugin]
vkmap = '''
  setlocal nolist
  setlocal listchars=
  setlocal colorcolumn=""
'''


[[plugins]]
repo = 'paroxayte/vwm.vim'
on_source = 'vkmap.vim'

# Delete buffer without closing window (tig-explorer dependency)
[[plugins]]
repo = 'rbgrouleff/bclose.vim'
on_cmd = ['Bclose']
hook_add = '''
  let g:bclose_no_plugins_maps = 1
  nnoremap <silent> sx  :<C-u>Bclose<CR>
'''

# --- }}}

# --- Interfaces {{{

# SKK imput method for Japanese
[[plugins]]
repo = 'tyru/eskk.vim'
on_map = {ic = '<Plug>'}
hook_add = '''
  imap <C-j>  <Plug>(eskk:toggle)
  cmap <C-j>  <Plug>(eskk:toggle)
'''
hook_source = 'source $VIM_CONFIG_HOME/rc/plugins/eskk.vim'

# Smart commenter
[[plugins]]
repo = 'tyru/caw.vim'
depends = ['context_filetype.vim']
on_map = {nv = '<Plug>'}
hook_add = ''' "{{{
  let g:caw_no_default_keymappings = 1

  nmap <Leader>cc  <Plug>(caw:hatpos:toggle)
  xmap <Leader>cc  <Plug>(caw:hatpos:toggle)
  nmap <Leader>ca  <Plug>(caw:dollarpos:toggle)
  xmap <Leader>ca  <Plug>(caw:dollarpos:toggle)
  nmap <Leader>cb  <Plug>(caw:box:toggle)
  xmap <Leader>cb  <Plug>(caw:box:toggle)
  nmap <Leader>cw  <Plug>(caw:wrap:toggle)
  xmap <Leader>cw  <Plug>(caw:wrap:toggle)
  nmap <Leader>c]  <Plug>(caw:jump:comment-next)
  nmap <Leader>c[  <Plug>(caw:jump:comment-prev)
"}}} '''

# Make blockwise visual mode more useful
[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {nx = '<Plug>'}
hook_add = '''
  xmap I  <Plug>(niceblock-I)
  xmap A  <Plug>(niceblock-A)
'''

# Vim motions on speed!
[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = {n = '<Plug>'}
hook_add = ''' "{{{
  " Search and jump
  nmap sf <Plug>(easymotion-overwin-f)
  nmap ss <Plug>(easymotion-overwin-f2)
  vmap ss <Plug>(easymotion-s2)
  omap ss <Plug>(easymotion-s2)

  map  sh <Plug>(easymotion-linebackward)
  map  sj <Plug>(easymotion-j)
  map  sk <Plug>(easymotion-k)
  map  sl <Plug>(easymotion-lineforward)

  map  s/ <Plug>(easymotion-sn)
  omap s/ <Plug>(easymotion-tn)
  map  sn <Plug>(easymotion-next)
  map  sp <Plug>(easymotion-prev)

  " smart f & F (visual mode and operator mode)
  nmap f <Plug>(easymotion-sl)
  omap f <Plug>(easymotion-bd-fl)
  xmap f <Plug>(easymotion-bd-fl)
  omap F <Plug>(easymotion-Fl)
  xmap F <Plug>(easymotion-Fl)
  omap t <Plug>(easymotion-tl)
  xmap t <Plug>(easymotion-tl)
  omap T <Plug>(easymotion-Tl)
  xmap T <Plug>(easymotion-Tl)
"}}} '''
hook_source = ''' "{{{
  " Disable default mappings
  let g:EasyMotion_do_mapping = 0
  " Do not shade
  let g:EasyMotion_do_shade = 0
  " Use uppercase target labels (and type as a lowercase)
  let g:EasyMotion_use_upper = 1
  " Characters used for target labels
  let g:EasyMotion_keys = ';HKLYUIONM,WERTXCVBASDGJF'
  " Smartcase ('v' matches both 'v' and 'V', while 'V' does only 'V')
  let g:EasyMotion_smartcase = 1
  " Smartsign ('1' matches both '1' and '!' -> not used)
  let g:EasyMotion_use_smartsign_us = 0
  " keep cursor column
  let g:EasyMotion_startofline = 0
  " Don't skip folded line
  let g:EasyMotion_skipfoldedline = 0
  " pseudo-migemo
  let g:EasyMotion_use_migemo = 1
  " Jump to first with enter & space
  let g:EasyMotion_space_jump_first = 1
  " Prompt
  let g:EasyMotion_prompt = 'Search for {n} chars> '
"}}} '''

# Move to the edge!
[[plugins]]
repo = 'haya14busa/vim-edgemotion'
on_map = {nv = '<Plug>'}
hook_add = ''' "{{{
  map  gj  <Plug>(edgemotion-j)
  map  gk  <Plug>(edgemotion-k)
  xmap gj  <Plug>(edgemotion-j)
  xmap gk  <Plug>(edgemotion-k)
"}}} '''

# Accerlerate up-down moving!
[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

#  Extended J command
[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = {nx = '<Plug>'}
hook_add = ''' "{{{
  nmap J  <Plug>(jplus)
  vmap J  <Plug>(jplus)

  " Insert one or more characters when join
  nmap <Leader>J  <Plug>(jplus-input)
  vmap <Leader>J  <Plug>(jplus-input)
"}}} '''

# Fast folding
[[plugins]]
repo = 'Konfekt/FastFold'
on_event = 'BufEnter'
hook_add = ''' "{{{
  " Global variables
  let g:fastfold_savehook = 1
  let g:fastfold_fold_command_suffixes =  ['x','X','a','A','o','O','c','C']
  let g:fastfold_fold_movement_commands = [']z', '[z', 'zj', 'zk']
  " Update folds
  nmap zuz      <Plug>(FastFoldUpdate)
  " Create a fold text object
  xnoremap iz  :<C-u>FastFoldUpdate<CR><ESC>:<C-u>normal! ]zv[z<CR>
  xnoremap az  :<C-u>FastFoldUpdate<CR><ESC>:<C-u>normal! ]zV[z<CR>
"}}} '''

# Calendar
[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = 'Calendar'
hook_source = '''
  let g:calendar_google_calendar = 1
  let g:calendar_google_task = 1
'''

# Set the buffer filetype based on the code block
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_event = 'BufEnter'

# --- }}}

# --- Textobj/Operator extensions {{{

[[plugins]]
repo = 'machakann/vim-sandwich'
#on_map = {nxo = '<Plug>'}
on_path = '.*'
hook_add = ''' "{{{
	let g:sandwich_no_default_key_mappings = 1

  silent! nmap <unique><silent> sd <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
  silent! nmap <unique><silent> sr <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
  silent! nmap <unique><silent> sdb <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
  silent! nmap <unique><silent> srb <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)

  " operator
  silent! nmap <unique> sa <Plug>(operator-sandwich-add)
  silent! xmap <unique> sa <Plug>(operator-sandwich-add)
  silent! omap <unique> sa <Plug>(operator-sandwich-g@)

  silent! xmap <unique> sd <Plug>(operator-sandwich-delete)

  silent! xmap <unique> sr <Plug>(operator-sandwich-replace)

  " textobj
  silent! omap <unique> ib <Plug>(textobj-sandwich-auto-i)
  silent! xmap <unique> ib <Plug>(textobj-sandwich-auto-i)
  silent! omap <unique> ab <Plug>(textobj-sandwich-auto-a)
  silent! xmap <unique> ab <Plug>(textobj-sandwich-auto-a)

  silent! omap <unique> is <Plug>(textobj-sandwich-query-i)
  silent! xmap <unique> is <Plug>(textobj-sandwich-query-i)
  silent! omap <unique> as <Plug>(textobj-sandwich-query-a)
  silent! xmap <unique> as <Plug>(textobj-sandwich-query-a)
"}}} '''
hook_source = ''' "{{{
  let g:textobj#sandwich#stimeoutlen = 100

  " Custom recipes
  let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
  let g:sandwich#recipes += [{'buns' : ['「', '」']}]
  let g:sandwich#recipes += [{'buns' : ['【', '】']}]
  let g:sandwich#recipes += [{'buns' : ['（', '）']}]
  let g:sandwich#recipes += [{'buns' : ['『', '』']}]

  " \(, \) pair and \%(, \) pair in Vim script
  let g:sandwich#recipes += [
        \ {'buns' : ['\(', '\)'],  'filetype' : ['vim'], 'nesting' : 1},
        \ {'buns' : ['\%(', '\)'], 'filetype' : ['vim'], 'nesting' : 1},
        \ ]
"}}} '''

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = ['vim-operator-user']
hook_add = '''
  nmap R <Plug>(operator-replace)
  xmap R <Plug>(operator-replace)
'''

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = ['vim-textobj-user']
on_func = 'textobj#user#'
on_map = {ox = '<Plug>'}
hook_add = ''' "{{{
  let g:textobj_entire_no_default_key_mappings = 1
  omap ae <Plug>(textobj-entire-a)
  omap ie <Plug>(textobj-entire-i)
  xmap ae <Plug>(textobj-entire-a)
  xmap ie <Plug>(textobj-entire-i)
"}}} '''

[[plugins]]
repo = 'kana/vim-textobj-line'
depends = ['vim-textobj-user']
on_map = {ox = '<Plug>'}
hook_add = ''' "{{{
  let g:textobj_line_no_default_key_mappings = 1
  omap al <Plug>(textobj-line-a)
  omap il <Plug>(textobj-line-i)
  xmap al <Plug>(textobj-line-a)
  xmap il <Plug>(textobj-line-i)
"}}} '''

[[plugins]]
repo = 'thinca/vim-textobj-comment'
depends = ['vim-textobj-user']
on_map = {ox = '<Plug>'}
hook_add = ''' "{{{
  let g:textobj_comment_no_default_key_mappings = 1
  omap ac <Plug>(textobj-comment-a)
  omap ic <Plug>(textobj-comment-i)
  xmap ac <Plug>(textobj-comment-a)
  xmap ic <Plug>(textobj-comment-i)
"}}} '''

[[plugins]]
repo = 'kana/vim-textobj-fold'
depends = ['vim-textobj-user']
on_map = {ox = '<Plug>'}
hook_add = ''' "{{{
  let g:textobj_fold_no_default_key_mappings = 1
  omap az <Plug>(textobj-fold-a)
  omap iz <Plug>(textobj-fold-i)
  xmap az <Plug>(textobj-fold-a)
  xmap iz <Plug>(textobj-fold-i)
"}}} '''

[[plugins]]
repo = 'mattn/vim-textobj-url'
depends = 'vim-textobj-user'
on_map = {ox = '<Plug>'}
hook_add = ''' "{{{
  let g:textobj_url_no_default_key_mappings = 1
  omap au <Plug>(textobj-url-a)
  omap iu <Plug>(textobj-url-i)
  xmap au <Plug>(textobj-url-a)
  xmap iu <Plug>(textobj-url-i)
"}}} '''

[[plugins]]
repo = 'machakann/vim-textobj-delimited'
on_map = {ox = '<Plug>'}
hook_add = ''' "{{{
  let g:textobj_delimited_no_defautl_key_mappings = 1

  omap ad <Plug>(textobj-delimited-forward-a)
  omap id <Plug>(textobj-delimited-forward-i)
  xmap ad <Plug>(textobj-delimited-forward-a)
  xmap id <Plug>(textobj-delimited-forward-i)
"}}} '''

# --- Expand region
[[plugins]]
repo = 'terryma/vim-expand-region'
depends = ['vim-sandwich', 'vim-textobj-delimited']
on_map = {x = '<Plug>'}
hook_add = ''' "{{{
  "ad: textobj-delimeted"
  "ib: sandwich"
  let g:expand_region_text_objects = {
        \ 'iw'  : 0,
        \ 'iW'  : 0,
        \ 'iu'  : 0,
        \ 'ad'  : 1,
        \ 'ib'  : 1,
        \ 'il'  : 1,
        \ 'ip'  : 0,
        \ 'ie'  : 0,
        \ }

  xmap v  <Plug>(expand_region_expand)
  xmap V  <Plug>(expand_region_shrink)
"}}} '''

# --- }}}

# --- VCS (Git) {{{

# Git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Git', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge', 'Gpull',
          'Grebase', 'Gpush', 'Gfetch', 'Ggrep', 'Glgrep', 'Glog', 'Gllog',
          'Gedit', 'Gsplit', 'Gvsplit', 'Gpedit', 'Gtabedit', 'Gpedit',
          'Gread', 'Gwrite', 'Gwq', 'Gdiff', 'Gsdiff', 'Gvdiff', 'Gmove',
          'Grename', 'Gblame', 'Gbrowse']

# Use Tig as a git client on vim
[[plugins]]
repo = 'iberianpig/tig-explorer.vim'
depends = ['bclose.vim']
on_cmd = ['TigOpenCurrentFile', 'TigOpenProjectRootDir', 'TigGrep', 'TigGrep',
          'TigGrepResume', 'TigBlame']
hook_add = ''' "{{{
  let g:tig_explorer_keymap_edit    = '<C-o>'
  let g:tig_explorer_keymap_tabedit = '<C-t>'
  let g:tig_explorer_keymap_split   = '<C-s>'
  let g:tig_explorer_keymap_vsplit  = '<C-v>'

  nnoremap <silent> <Space>tb  :TigBlame<CR>
  nnoremap <silent> <Space>tt  :TigOpenCurrentFile<CR>
  nnoremap <silent> <Space>tp  :TigOpenProjectRootDir<CR>
  nnoremap <silent> <Space>t/  :TigGrep<CR>
  nnoremap <silent> <Space>t*  :<C-u>:TigGrep<Space><C-R><C-W><CR>
  vnoremap <silent> <Space>t*  y:TigGrep<Space><C-R>"<CR>
  nnoremap <silent> <Space>tr  :TigGrepResume<CR>
"}}} '''

# More pleasant editing on commit messages
[[plugins]]
repo = 'rhysd/committia.vim'
on_path = 'COMMIT_EDITMSG'
hook_source = '''
  let g:committia_min_window_width = 100
'''

# --- }}}

# --- Filetypes, Syntax {{{

# LaTeX
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_source = 'source $VIM_CONFIG_HOME/rc/plugins/vimtex.vim'

# Python
[[plugins]]
repo = 'tmhedberg/SimpylFold'
on_ft = 'python'

[[plugins]]
repo = 'raimon49/requirements.txt.vim'
on_ft = 'requirements'

# CSV
[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = 'csv'

# Markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'
hook_add = ''' "{{{
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
  let g:vim_markdown_conceal = 0
"}}} '''

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = 'markdown'

# Generate table of contents for Markdown file
[[plugins]]
repo = 'mzlogin/vim-markdown-toc'
on_cmd = ['GenTocGFM', 'GenTocRedcarpet', 'GenTocGitLab', 'UpdateToc']
hook_source = '''
  let g:vmt_auto_update_on_save = 0
'''

# Markdown live preview
[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_ft = 'markdown'
depends = ['markdown-preview.vim']

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = 'markdown'
hook_source = '''
  let g:mkdp_refresh_slow = 1
'''

# Hex editor
[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'
hook_add = '''
  let g:vinarise_enable_auto_detect = 1
'''

# --- }}}

#-----------------------------------------------------------------------------
# vim: foldmethod=marker
