#------------------------------------------------------------------------------
# Auto completion
#------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  source $XDG_CONFIG_HOME/nvim/rc/plugins/deoplete.rc.vim
'''

#------------------------------------------------------------------------------
# Snippets
#------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
  " <C-k> to insert a snippet
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)

  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#expand_word_boundary = 1
  let g:neosnippet#snippets_directory = '~/.config/nvim/snippets'
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

#------------------------------------------------------------------------------
# Denite
#------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = '''
  call echodoc#enable()
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hood_post_source = 'source ~/.config/nvim/rc/plugins/denite.rc.vim'
hook_add = '''
  nnoremap [denite] <Nop>
  nmap <Space> [denite]
  nmap <silent> [denite]ft : <C-u>Denite filetype<CR>
  nmap <silent> [denite]ff : <C-u>Denite file_rec<CR>
  nmap <silent> [denite]y  : <C-u>Denite neoyank<CR>
  nmap <silent> [denite]G
    \ : <C-u>Denite grep -mode=normal -buffer-name=search-buffer-denite<CR>

  nmap <silent> [denite]rr
    \ : <C-u>Denite -resume -buffer-name=search-buffer-denite<CR>
  nmap <silent> [denite]rn : <C-u>Denite -resume 
    \  -buffer-name=search-buffer-denite -select=+1 -immediately<CR>
  nmap <silent> [denite]rp : <C-u>Denite -resume
    \ -buffer-name=search-buffer-denite -select=-1 -immediately<CR>

  " Substitute search commands by denite
  nnoremap <silent> / :<C-u>Denite -buffer-name=search -auto-highlight line<CR>
  nnoremap <silent> * :<C-u>DeniteCursorWord -buffer-name=search -auto-highlight -mode=normal line<CR>
'''

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'

#-----------------------------------------------------------------------------
# Smart commenter
#-----------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/caw.vim'
on_map = {nx = '<Plug>'}
hook_add = '''
  function! InitCaw() abort
    if !&l:modifiable
      silent! nunmap <buffer> gc
      silent! xunmap <buffer> gc
      silent! nunmap <buffer> gcc
      silent! xunmap <buffer> gcc
    else
      nmap <buffer> gc <Plug>(caw:prefix)
      xmap <buffer> gc <Plug>(caw:prefix)
      nmap <buffer> gcc <Plug>(caw:hatpos:toggle)
      xmap <buffer> gcc <Plug>(caw:hatpos:toggle)
    endif
  endfunction
  autocmd MyAutoCmd FileType * call InitCaw()
  call InitCaw()
'''
